# Permalinks
permalink:           pretty

# Setup
title:               Jonathan Dawson
tagline:             An Awesome Data Science Blog
url:                 http://jedawson.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jonathan Dawson
  url:               https://www.linkedin.com/in/jonathanedawson/
  email:             dawsonjed@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jedawson

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
